const modes={
  night:[['Noche profunda','El contraste clásico de Beatplace.'],['Noche índigo','Un acento violeta para sesiones largas.'],['Noche bosque','Verdes cálidos y orgánicos.']],
  day:[['Día claro','Marfil suave y texto con alto contraste.'],['Día solar','Arena y naranja para crear con energía.'],['Día bruma','Azules calmados para concentrarte.']]
};
export function installAppearance(C){Object.defineProperties(C.prototype,Object.getOwnPropertyDescriptors({
  initAppearance(){if(this.appearance)return;let saved={};try{saved=JSON.parse(localStorage.getItem(this.storageKey+'-appearance')||'{}');}catch{}const migrated=saved.version===2;const hasStyle=Number.isInteger(Number(saved.style));this.appearance=migrated?{mode:saved.mode==='day'?'day':'night',style:hasStyle?Math.min(2,Math.max(0,Number(saved.style))):1,user:saved.user||null,language:saved.language==='en'?'en':'es'}:{mode:'night',style:1,user:saved.user||null,language:'es'};if(!migrated)this.saveAppearance();},
  saveAppearance(){try{localStorage.setItem(this.storageKey+'-appearance',JSON.stringify({...this.appearance,version:2}));}catch{}},
  themeClass(){this.initAppearance();return `theme-${this.appearance.mode} theme-${this.appearance.mode}-${this.appearance.style}`;},
  headerActions(){this.initAppearance();const u=this.appearance.user;const palette='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3C8.8 3 3 8.2 3 15.1 3 20.4 7 24 11.8 24h1.5c1.1 0 1.8 1.1 1.4 2.1-.6 1.6.6 2.9 2.4 2.9 6.7 0 12-5.8 12-12.9C29 8.9 23.2 3 16 3Z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="9.4" cy="14" r="1.7" fill="#ff815d" stroke="none"/><circle cx="14.2" cy="9.2" r="1.7" fill="#a991ff" stroke="none"/><circle cx="20.5" cy="10.4" r="1.7" fill="#63c9c0" stroke="none"/><circle cx="23.3" cy="16.6" r="1.7" fill="#f0cd6f" stroke="none"/></svg>';return `<button class="appearance-button palette-button" data-appearance="open" aria-label="Cambiar colores">${palette}</button><button class="language-button" data-appearance="language" aria-label="Cambiar idioma">${this.appearance.language==='es'?'ES':'EN'}</button><button class="upload-btn" data-action="upload">⇧<span>Subir beat</span></button>${u?`<button class="avatar" data-appearance="account" aria-label="Abrir cuenta">${u.initials||'TÚ'}</button>`:`<button class="auth-entry" data-appearance="auth"><i>●</i>Acceder</button>`}`;},
  appearanceModal(){const a=this.appearance;const options=modes[a.mode];this.modal(`<div class="eyebrow">AJUSTA TU ESPACIO</div><h2>Aspecto</h2><div class="mode-switch" role="group" aria-label="Modo de color"><button data-appearance-mode="night" class="${a.mode==='night'?'selected':''}">☾ Noche</button><button data-appearance-mode="day" class="${a.mode==='day'?'selected':''}">☀ Día</button></div><div class="style-options">${options.map(([name,description],i)=>`<button data-appearance-style="${i}" class="${a.style===i?'selected':''}"><span class="theme-preview preview-${a.mode}-${i}"><i></i><b></b><em></em></span><strong>${name}</strong><small>${description}</small>${a.style===i?'<mark>✓</mark>':''}</button>`).join('')}</div><p class="modal-note">La elección se conserva solo en este dispositivo.</p>`);},
  accountModal(){const u=this.appearance.user;this.modal(`<div class="eyebrow">TU CUENTA</div><h2>Hola, ${this.escapeUser(u.name)}.</h2><div class="account-card"><span class="account-avatar">${this.escapeUser(u.initials)}</span><div><strong>${this.escapeUser(u.name)}</strong><small>${this.escapeUser(u.email)}</small></div></div><button class="secondary wide" data-appearance="profile">Ver mi perfil</button><button class="logout-button wide" data-appearance="logout">Cerrar sesión</button>`);},
  escapeUser(value){return String(value||'Tú').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));},
  authModal(kind='login'){const register=kind==='register';this.modal(`<div class="eyebrow">${register?'EMPIEZA A CREAR':'QUÉ BUENO VERTE'}</div><h2>${register?'Crea tu cuenta.':'Inicia sesión.'}</h2><p class="subtext">${register?'Guarda tus gustos, conecta con creadores y comparte tus sonidos.':'Tu comunidad y tus gustos te están esperando.'}</p><form id="auth-form" data-auth-kind="${kind}">${register?'<label>Nombre o nombre artístico<input name="name" autocomplete="name" maxlength="60" required placeholder="Cómo quieres que te vean"></label>':''}<label>Correo electrónico<input name="email" type="email" autocomplete="email" maxlength="254" required placeholder="tu@correo.com"></label><label>Contraseña<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" minlength="8" required placeholder="Mínimo 8 caracteres"></label><p class="auth-error" role="alert"></p><button class="primary wide" type="submit">${register?'Crear cuenta':'Entrar'} ↗</button></form><p class="auth-switch">${register?'¿Ya tienes cuenta?':'¿Primera vez en Beatplace?'} <button data-appearance="${register?'login':'register'}">${register?'Entrar':'Regístrate'}</button></p><small class="modal-note">${this.hasAttribute('demo')?'Demo local: no se envía información a ningún servidor.':'Conecta onAuth para validar la cuenta en tu servicio.'}</small>`);},
  async authSubmit(e){const f=e.target;if(f.id!=='auth-form')return false;e.preventDefault();const data=new FormData(f),kind=f.dataset.authKind,email=String(data.get('email')).trim().toLowerCase(),password=String(data.get('password'));const error=f.querySelector('.auth-error'),button=f.querySelector('[type=submit]');if(!/^\S+@\S+\.\S+$/.test(email)){error.textContent='Ingresa un correo electrónico válido.';return true;}if(password.length<8){error.textContent='La contraseña debe tener al menos 8 caracteres.';return true;}button.disabled=true;try{let user;if(this.hasAttribute('demo')){const name=kind==='register'?String(data.get('name')).trim():'Creador/a';if(kind==='register'&&!name){throw Error('Escribe cómo quieres que te vean.');}user={id:'demo-'+email,name, email, initials:name.split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase()||'TÚ'};}else{if(typeof this.onAuth!=='function')throw Error('Conecta el servicio de autenticación de la app para continuar.');user=await this.onAuth({action:kind,email,password,name:kind==='register'?String(data.get('name')).trim():undefined});if(!user?.id)throw Error('El servicio de autenticación debe devolver un usuario.');}this.appearance.user=user;this.saveAppearance();this.closeModal();this.render();this.emit('auth',{action:kind,user});this.toast(kind==='register'?'Tu cuenta está lista. Bienvenido/a a Beatplace.':'Sesión iniciada.');}catch(err){error.textContent=err.message||'No se pudo completar la operación.';}finally{if(button.isConnected)button.disabled=false;}return true;},
  async logout(){try{if(!this.hasAttribute('demo')){if(typeof this.onAuth!=='function')throw Error('Conecta el servicio de autenticación para cerrar la sesión.');await this.onAuth({action:'logout'});}this.appearance.user=null;this.saveAppearance();this.closeModal();this.render();this.emit('auth',{action:'logout'});this.toast('Sesión cerrada.');}catch(err){this.toast(err.message||'No se pudo cerrar la sesión.');}},
  translateInterface(){if(this.appearance?.language!=='en')return;const words={'Inicio':'Home','Crear':'Create','Todos los beats':'All beats','Productores':'Producers','Favoritos':'Favorites','Mis compras':'My purchases','Biblioteca':'Library','Tu comunidad.':'Your community.','Ideas que se comparten. Música que se siente.':'Ideas to share. Music to feel.','Para ti':'For you','Siguiendo':'Following','EN TU FRECUENCIA':'IN YOUR FREQUENCY','¿En qué estás creando hoy?':'What are you creating today?','Compartir un beat':'Share a beat','Foto / idea':'Photo / idea','Publicar ↗':'Publish ↗','Personalizar':'Customize','Tus gustos':'Your tastes','Conecta con creadores':'Connect with creators','Suena en tu círculo':'Playing in your circle','Tu próximo track empieza aquí.':'Your next track starts here.','Abrir herramientas ↗':'Open tools ↗','Subir beat':'Upload beat','Acceder':'Sign in','Tu talento tiene valor.':'Your talent has value.','Comparte tu sonido.':'Share your sound.','Conecta con nuevos artistas.':'Connect with new artists.','Vender mis beats':'Sell my beats','Dale play a tu próxima idea':'Play your next idea','Elige un beat para escuchar':'Choose a beat to listen to','Beats':'Beats','TÚ':'YOU','Cerrar sesión':'Sign out','Herramientas':'Tools','Explorar beats':'Explore beats'};const walker=document.createTreeWalker(this.shadowRoot,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const exact=node.nodeValue.trim();if(words[exact])node.nodeValue=node.nodeValue.replace(exact,words[exact]);}this.shadowRoot.querySelectorAll('[placeholder]').forEach(el=>{if(el.placeholder==='Busca tu próximo sonido…')el.placeholder='Find your next sound…';if(el.placeholder==='Escribe un comentario…')el.placeholder='Write a comment…';});},
  appearanceClick(e){const button=e.target.closest('button');if(!button)return false;const d=button.dataset;if(d.appearance){if(d.appearance==='open')this.appearanceModal();if(d.appearance==='language'){this.appearance.language=this.appearance.language==='es'?'en':'es';this.saveAppearance();this.render();}if(d.appearance==='auth')this.authModal();if(d.appearance==='account')this.accountModal();if(d.appearance==='login')this.authModal('login');if(d.appearance==='register')this.authModal('register');if(d.appearance==='logout')this.logout();if(d.appearance==='profile'){this.closeModal();this.state.view='library';this.render();}return true;}if(d.appearanceMode){this.appearance.mode=d.appearanceMode;this.appearance.style=0;this.saveAppearance();this.render();this.appearanceModal();return true;}if(d.appearanceStyle){this.appearance.style=Number(d.appearanceStyle);this.saveAppearance();this.render();this.appearanceModal();return true;}return false;}
}));}

