import {installSocial} from './social.js';
import {installAppearance} from './appearance.js';
import {genres,producers,demoBeats,filterBeats,splitPayment,escapeHTML as esc} from './core.js';
const asset=name=>new URL(`./assets/${name}`,import.meta.url).href;
const stylesheetUrl=new URL('./styles.css',import.meta.url);
const socialStylesheetUrl=new URL('./social.css',import.meta.url);
const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',bag:'<path d="M4 7h16l1 14H3Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M2 21v-3a7 7 0 0 1 14 0v3M16 5a3 3 0 0 1 0 6M19 14a5 5 0 0 1 3 4v3"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',play:'<path d="m8 4 13 8-13 8Z" fill="currentColor" stroke="none"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',next:'<path d="m5 5 10 7-10 7Z" fill="currentColor"/><path d="M19 5v14"/>',prev:'<path d="m19 5-10 7 10 7Z" fill="currentColor"/><path d="M5 5v14"/>',volume:'<path d="M3 9h4l5-5v16l-5-5H3ZM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',check:'<path d="m5 12 4 4L19 6"/>',music:'<path d="M9 18V5l11-2v13M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/>'};
const icon=(n)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.music}</svg>`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const time=n=>`${Math.floor((n||0)/60)}:${String(Math.floor((n||0)%60)).padStart(2,'0')}`;
class BeatPlace extends HTMLElement{
 constructor(){super();this.attachShadow({mode:'open'});this._beats=[];this._styles="";this._stylesPromise=null;this.state={view:'discover',genre:'Todos',query:'',sort:'popular',favorites:[],purchased:[],current:null,playing:false};this.audio=new Audio();this.audio.preload='metadata';this.audio.volume=.7;this.urls=[];this._onClick=this.onClick.bind(this);this._onInput=this.onInput.bind(this);this._onSubmit=this.onSubmit.bind(this);this.audio.addEventListener('timeupdate',()=>this.updateProgress());this.audio.addEventListener('loadedmetadata',()=>this.updateProgress());this.audio.addEventListener('ended',()=>this.next(1));this.audio.addEventListener('error',()=>{this.state.playing=false;this.updatePlayer();this.toast('No se pudo cargar la vista previa de audio.');});this.audio.addEventListener('pause',()=>{this.state.playing=false;this.updatePlayer();});this.audio.addEventListener('play',()=>{this.state.playing=true;this.updatePlayer();});}
 connectedCallback(){if(this._connected)return;this._connected=true;if(!this._configured)this._beats=this.hasAttribute('demo')?demoBeats.map((b,i)=>({...b,previewUrl:asset(b.audioFile||`preview-${i%3}.wav`)})):[];try{const s=JSON.parse(localStorage.getItem(this.storageKey)||'{}');this.state.favorites=Array.isArray(s.favorites)?s.favorites:[];this.state.purchased=this.hasAttribute("demo")&&Array.isArray(s.purchased)?s.purchased:[];}catch{}this.shadowRoot.addEventListener('click',this._onClick);this.shadowRoot.addEventListener('input',this._onInput);this.shadowRoot.addEventListener('change',this._onInput);this.shadowRoot.addEventListener('submit',this._onSubmit);this.initAppearance();this.initSocial();this.render();}
 disconnectedCallback(){this.stopTool?.();this.revealObserver?.disconnect();this.audio.pause();this.shadowRoot.removeEventListener('click',this._onClick);this.shadowRoot.removeEventListener('input',this._onInput);this.shadowRoot.removeEventListener('change',this._onInput);this.shadowRoot.removeEventListener('submit',this._onSubmit);clearTimeout(this.toastTimer);this._connected=false;}
 get allProducers(){return [...new Map(this._beats.map(b=>{const p=this.producer(b);return [p.id,p];})).values()];}
 get storageKey(){return this.getAttribute('storage-key')||'beatplace-v1';}
 set beats(value){if(!Array.isArray(value))throw new TypeError('beats debe ser un array');const ids=new Set();this._beats=value.map(b=>{if(!b.id||ids.has(b.id)||!b.title||!Number.isFinite(b.price)||b.price<0)throw new TypeError('Cada beat necesita id único, title y price válido');ids.add(b.id);return {...b};});this._configured=true;if(this.isConnected)this.render();}
 get beats(){return this._beats.map(b=>({...b}));}
 set purchasedIds(ids){this.state.purchased=[...new Set(ids)];if(this.isConnected)this.render();}
 emit(name,detail){this.dispatchEvent(new CustomEvent(`beatplace:${name}`,{detail,bubbles:true,composed:true}));}
 save(){try{localStorage.setItem(this.storageKey,JSON.stringify({favorites:this.state.favorites,purchased:this.hasAttribute('demo')?this.state.purchased:[]}));}catch{}}
 producer(b){return producers.find(p=>p.id===b.producerId)||{id:b.producerId,name:b.producerName||'Productor independiente',initials:'BP',color:'#ff9b73',tag:'Sonidos originales, nuevas posibilidades.',city:'Productor independiente'};}
 art(b,cls=''){return `<img class="art ${cls}" src="${esc(this.safeUrl(b.artworkUrl)||asset(`${b.art||'midnight'}.svg`))}" alt="Portada de ${esc(b.title)}" loading="lazy">`;}
 safeUrl(url){if(typeof url!=="string"||!url.trim())return "";try{const u=new URL(url,location.href);return ['https:','http:','blob:'].includes(u.protocol)?u.href:'';}catch{return '';}}
 async prepareStyles(){if(this._styles)return true;if(!this._stylesPromise)this._stylesPromise=Promise.all([fetch(stylesheetUrl).then(r=>r.text()),fetch(socialStylesheetUrl).then(r=>r.text())]).then(([base,social])=>{this._styles=base.replace('@import url("./social.css");','')+social;return true;}).catch(()=>false);const ready=await this._stylesPromise;if(ready&&this.isConnected)this.render();return ready;}
render(){if(!this._styles){this.prepareStyles();return;}this.shadowRoot.innerHTML=`<style>${this._styles}</style><div class="shell ${this.themeClass()}"><aside class="sidebar"><button class="brand wild-brand" data-view="discover" aria-label="Wild Sound inicio"><img src="${asset('wild-company-mark.png')}" alt="Wild Company"><span><b>WILD</b> SOUND<small>BY WILD COMPANY</small></span></button><span class="nav-label">TU PRÓXIMO SONIDO</span><nav>${this.nav('discover','home','Inicio')}${this.nav('create','music','Crear')}${this.nav('catalog','grid','Todos los beats')}${this.nav('producers','users','Productores')}<span class="nav-label library-label">TU ESPACIO</span>${this.nav('favorites','heart','Favoritos')}${this.nav('library','bag','Mis compras')}</nav><div class="creator-box"><div class="mini-disc"></div><h3>Tu talento tiene valor.</h3><p>Comparte tu sonido.<br>Conecta con nuevos artistas.</p><button data-action="upload">Vender mis beats ${icon('arrow')}</button><small>90% para ti. 100% tu sonido.</small></div><div class="sidebar-foot"><span class="status-dot"></span>Hecho para crear</div></aside><div class="workspace"><header><button class="mobile-brand" data-view="discover" aria-label="Wild Sound inicio"><img src="${asset('wild-company-mark.png')}" alt="Wild Company"><span><b>WILD</b> SOUND<small>BY WILD COMPANY</small></span></button><div class="search-wrap">${icon('search')}<input id="search" type="search" aria-label="Buscar beats, productores o BPM" placeholder="Busca tu próximo sonido…" value="${esc(this.state.query)}"></div><div class="header-actions">${this.headerActions()}</div></header><main id="main">${this.content()}</main><footer class="page-footer"><span>Sonidos independientes. Posibilidades infinitas.</span><span>WILD SOUND © 2026</span></footer></div><section class="player" aria-label="Reproductor de beats"></section><nav class="mobile-nav">${this.nav('discover','home','Inicio')}${this.nav('catalog','grid','Beats')}${this.nav('create','music','Crear')}${this.nav('favorites','heart','Favoritos')}${this.nav('library','bag','Biblioteca')}</nav><div class="toast" role="status" aria-live="polite"></div><div id="modal-root"></div></div>`;this.updatePlayer();this.translateInterface?.();this.animateContent();this.shadowRoot.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Escape'){e.target.value='';this.state.query='';this.updateContent();}});}
 nav(view,i,label){return `<button class="nav-item ${this.state.view===view?'active':''}" data-view="${view}" ${this.state.view===view?'aria-current="page"':''}>${icon(i)}<span>${label}</span>${view==='favorites'&&this.state.favorites.length?`<small>${this.state.favorites.length}</small>`:''}</button>`;}
 content(){const s=this.state;if(s.view==='discover')return this.feed();if(s.view==='create')return this.createPage();if(s.view==='producers')return `<div class="eyebrow">LA GENTE DETRÁS DEL SONIDO</div><h1>Productores independientes<span class="accent">.</span></h1><p class="subtext">Encuentra a quien entiende tu próximo proyecto.</p><div class="producer-grid">${this.allProducers.map(p=>this.producerCard(p)).join('')}</div>`;if(s.view==='profile'){const p=producers.find(p=>p.id===s.profile)||this.producer(this._beats.find(b=>b.producerId===s.profile)||{});return `<button class="text-btn" data-view="producers">← Volver a productores</button><div class="profile"><div class="producer-avatar" style="--p:${p.color}">${esc(p.initials)}</div><div><div class="eyebrow">PRODUCTOR INDEPENDIENTE</div><h1>${esc(p.name)}</h1><p>${esc(p.tag)}</p><span class="subtext">${esc(p.city)}</span></div></div><h2>Beats de ${esc(p.name)}</h2>${this.list(this._beats.filter(b=>b.producerId===s.profile))}`;}
 const searching=!!s.query;const discover=s.view==='discover'&&!searching;let filtered=filterBeats(this._beats,{...s,likedOnly:s.view==='favorites'});if(s.view==='library')filtered=filtered.filter(b=>s.purchased.includes(b.id));return `${discover?this.hero():`<div class="eyebrow">${s.view==='library'?'TU COLECCIÓN':s.view==='favorites'?'GUARDA LO QUE TE MUEVE':'EXPLORA EL CATÁLOGO'}</div><h1>${searching?'Encuentra tu sonido':s.view==='library'?'Mis compras':s.view==='favorites'?'Tus favoritos':'Todos los beats'}<span class="accent">.</span></h1><p class="subtext">${s.view==='library'?'Tus licencias y beats en un solo lugar.':s.view==='favorites'?'Los beats que quieres volver a escuchar.':'Un nuevo ritmo puede ser el inicio de todo.'}</p>`}${discover?`<section class="genres"><div class="section-title"><h2>¿Qué vibra buscas?</h2><span>ENCUENTRA TU FRECUENCIA</span></div>${this.chips()}</section><section><div class="section-title"><h2>En el radar<span class="accent"> ↗</span></h2><button class="text-btn" data-view="catalog">Ver todos ${icon('arrow')}</button></div><div class="cards">${filtered.slice(0,4).map(b=>this.card(b)).join('')}</div></section>`:this.chips()}<section class="track-section"><div class="section-title"><h2>${discover?'Beats para tu próxima idea':`${filtered.length} ${filtered.length===1?'beat':'beats'}`}</h2><label class="sort-label"><span>Ordenar:</span><select id="sort" aria-label="Ordenar beats"><option value="popular" ${s.sort==='popular'?'selected':''}>Más populares</option><option value="price" ${s.sort==='price'?'selected':''}>Menor precio</option><option value="new" ${s.sort==='new'?'selected':''}>Más recientes</option></select></label></div>${this.list(filtered)}</section>${discover?`<section class="producer-strip"><div><div class="eyebrow">DE PERSONAS, PARA PERSONAS</div><h2>Detrás de cada beat,<br>hay un universo.</h2><button class="text-btn" data-view="producers">Conoce a los productores ${icon('arrow')}</button></div><div class="strip-people">${this.allProducers.map(p=>`<button data-profile="${esc(p.id)}"><span class="producer-avatar" style="--p:${p.color}">${esc(p.initials)}</span><strong>${esc(p.name)}</strong><small>Ver perfil ↗</small></button>`).join('')}</div></section>`:''}`;}
 hero(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span>INDEPENDIENTE POR NATURALEZA</div><h1>Tu próxima canción<br>empieza con un <em>beat.</em></h1><p>Sonidos originales de productores independientes.<br>Escucha, conecta y hazlo tuyo.</p><button class="primary" data-action="explore">Explorar beats ${icon('arrow')}</button><div class="hero-note"><span class="tiny-wave">▂▆▃▇▂</span> Un espacio para encontrar tu sonido.</div></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="vinyl"><div class="vinyl-label"><span>BEATPLACE</span><b>bp.</b><small>SIDE A · ORIGINAL SOUNDS</small></div></div><div class="floating-tag">VOL. 01 <span>SONIDOS SIN LÍMITES</span></div><div class="art-caption">PRESS PLAY.<br>MAKE SOMETHING.</div><span class="spark">✳</span></div></section>`;}
 chips(){return `<div class="chips" role="group" aria-label="Filtrar por género">${genres.map((g,i)=>`<button data-genre="${g}" class="chip ${this.state.genre===g?'selected':''}" aria-pressed="${this.state.genre===g}">${i===0?'✳ ':''}${g}</button>`).join('')}</div>`;}
 card(b){const p=this.producer(b);return `<article class="beat-card"><div class="cover">${this.art(b)}<span class="genre-badge">${esc(b.genre)}</span><button class="favorite ${this.state.favorites.includes(b.id)?'is-liked':''}" data-like="${esc(b.id)}" aria-label="Guardar ${esc(b.title)}" aria-pressed="${this.state.favorites.includes(b.id)}">${icon('heart')}</button><button class="cover-play" data-play="${esc(b.id)}" aria-label="Reproducir ${esc(b.title)}">${icon(this.state.current===b.id&&this.state.playing?'pause':'play')}</button></div><div class="card-title"><h3>${esc(b.title)}</h3><span>↗</span></div><button class="producer-link" data-profile="${esc(p.id)}">${esc(p.name)} <span class="verified">✦</span></button><div class="card-bottom"><span>${b.bpm} BPM <i>·</i> ${esc(b.key)}</span><button data-buy="${esc(b.id)}">${money(b.price)}</button></div></article>`;}
 list(beats){if(!beats.length)return `<div class="empty">${icon(this.state.view==='favorites'?'heart':'music')}<h3>${this.state.view==='library'?'Tu colección empieza aquí':'Todavía no hay beats aquí'}</h3><p>${this.state.query?'Prueba con otro nombre, productor o género.':'Explora el catálogo y encuentra tu próximo sonido.'}</p><button class="primary" data-action="reset">Explorar catálogo ${icon('arrow')}</button></div>`;return `<div class="track-table"><div class="table-head"><span>#</span><span>BEAT / PRODUCTOR</span><span>GÉNERO</span><span>BPM / TONALIDAD</span><span>LICENCIA DESDE</span><span></span></div>${beats.map((b,i)=>{const p=this.producer(b);return `<div class="track-row ${this.state.current===b.id?'current':''}"><button class="row-play" data-play="${esc(b.id)}" aria-label="Reproducir ${esc(b.title)}"><span>${String(i+1).padStart(2,'0')}</span>${icon(this.state.current===b.id&&this.state.playing?'pause':'play')}</button><div class="track-identity">${this.art(b)}<div><button class="track-title" data-play="${esc(b.id)}">${esc(b.title)}</button><button class="producer-link" data-profile="${esc(p.id)}">${esc(p.name)}</button></div></div><span class="row-genre">${esc(b.genre)}</span><span class="row-bpm">${b.bpm} <small>${esc(b.key)}</small></span><button class="price-btn" ${this.state.view==='library'?`data-license="${esc(b.id)}"`:`data-buy="${esc(b.id)}"`}>${icon(this.state.view==='library'?'check':'bag')}${this.state.view==='library'?'Ver licencia':money(b.price)}</button><button class="like-btn ${this.state.favorites.includes(b.id)?'is-liked':''}" data-like="${esc(b.id)}" aria-label="Guardar ${esc(b.title)}" aria-pressed="${this.state.favorites.includes(b.id)}">${icon('heart')}</button></div>`;}).join('')}</div>`;}
 producerCard(p){const beats=this._beats.filter(b=>b.producerId===p.id);return `<button class="producer-card" data-profile="${esc(p.id)}"><div class="producer-avatar" style="--p:${p.color}">${esc(p.initials)}</div><h2>${esc(p.name)} <span class="verified">✦</span></h2><p>${esc(p.tag)}</p><small>${esc(p.city)}</small><div>${beats.length} beats <span>Explorar perfil ↗</span></div></button>`;}
 updateContent(){const main=this.shadowRoot.getElementById('main');if(main){main.innerHTML=this.content();this.animateContent();}}
 updatePlayer(){const container=this.shadowRoot.querySelector('.player');if(!container)return;const b=this._beats.find(b=>b.id===this.state.current);container.innerHTML=`<div class="now-playing">${b?this.art(b):'<span class="player-placeholder">'+icon('music')+'</span>'}<div><strong>${b?esc(b.title):'Dale play a tu próxima idea'}</strong><small>${b?esc(this.producer(b).name):'Elige un beat para escuchar'}</small></div>${b?`<button class="like-btn ${this.state.favorites.includes(b.id)?'is-liked':''}" data-like="${esc(b.id)}" aria-label="Guardar beat">${icon('heart')}</button>`:''}</div><div class="transport"><div class="transport-buttons"><button data-action="prev" aria-label="Beat anterior" ${!b?'disabled':''}>${icon('prev')}</button><button class="main-play" data-action="toggle" aria-label="${this.state.playing?'Pausar':'Reproducir'}">${icon(this.state.playing?'pause':'play')}</button><button data-action="next" aria-label="Siguiente beat" ${!b?'disabled':''}>${icon('next')}</button></div><div class="timeline"><span id="elapsed">0:00</span><input id="seek" aria-label="Posición de reproducción" type="range" min="0" max="1000" value="0" ${!b?'disabled':''}><span id="duration">0:00</span></div></div><div class="volume">${icon('volume')}<input id="volume" aria-label="Volumen" type="range" min="0" max="1" step=".01" value="${this.audio.volume}"><span class="preview-label">PREVIEW</span></div>`;this.updateProgress();this.shadowRoot.querySelectorAll('[data-play]').forEach(el=>{const active=el.dataset.play===this.state.current;const svg=el.querySelector('svg');if(svg)svg.outerHTML=icon(active&&this.state.playing?'pause':'play');});this.shadowRoot.querySelectorAll('.track-row').forEach(el=>el.classList.toggle('current',el.querySelector('[data-play]')?.dataset.play===this.state.current));}
 updateProgress(){const root=this.shadowRoot;const duration=Number.isFinite(this.audio.duration)?this.audio.duration:0;const seek=root.getElementById('seek');if(seek){seek.value=duration?this.audio.currentTime/duration*1000:0;seek.style.setProperty('--progress',`${Number(seek.value)/10}%`);}const elapsed=root.getElementById('elapsed');if(elapsed)elapsed.textContent=time(this.audio.currentTime);const d=root.getElementById('duration');if(d)d.textContent=time(duration);}
 async play(id){const b=this._beats.find(x=>x.id===id);if(!b)return;if(this.state.current===id&&!this.audio.paused){this.audio.pause();return;}if(this.state.current!==id){const url=this.safeUrl(b.previewUrl);if(!url){this.toast('Este beat aún no tiene una vista previa disponible.');return;}this.state.current=id;this.audio.src=url;}try{await this.audio.play();this.emit('play',{beatId:id});}catch{this.toast('No se pudo reproducir el audio. Intenta nuevamente.');}this.updatePlayer();}
 next(direction){const i=this._beats.findIndex(b=>b.id===this.state.current);const b=this._beats[(i+direction+this._beats.length)%this._beats.length];if(b)this.play(b.id);}
 onInput(e){if(this.socialInput?.(e))return;if(e.target.id==='search'){this.state.query=e.target.value;this.updateContent();}if(e.target.id==='sort'){this.state.sort=e.target.value;this.updateContent();}if(e.target.id==='volume')this.audio.volume=Number(e.target.value);if(e.target.id==='seek'&&Number.isFinite(this.audio.duration))this.audio.currentTime=Number(e.target.value)/1000*this.audio.duration;if(e.target.name==='license'){this.selectedLicense=e.target.value;this.updateCheckout();}}
 onClick(e){if(this.socialClick?.(e))return;const el=e.target.closest('button');if(!el)return;if(el.dataset.view){this.state.view=el.dataset.view;this.state.query='';this.state.genre='Todos';this.render();}if(el.dataset.genre){this.state.genre=el.dataset.genre;this.updateContent();}if(el.dataset.play)this.play(el.dataset.play);if(el.dataset.like){const id=el.dataset.like;const a=this.state.favorites;this.state.favorites=a.includes(id)?a.filter(x=>x!==id):[...a,id];this.save();this.updateContent();this.updatePlayer();this.emit('favorite',{beatId:id,favorite:this.state.favorites.includes(id)});}if(el.dataset.profile){this.state.profile=el.dataset.profile;this.state.view='profile';this.render();}if(el.dataset.buy)this.checkout(el.dataset.buy);if(el.dataset.license)this.showLicense(el.dataset.license);switch(el.dataset.action){case'explore':this.state.view='catalog';this.render();break;case'reset':this.state.view='catalog';this.state.query='';this.state.genre='Todos';this.render();break;case'upload':this.upload();break;case'close':this.closeModal();break;case'toggle':if(this.state.current)this.play(this.state.current);else if(this._beats[0])this.play(this._beats[0].id);break;case'next':this.next(1);break;case'prev':this.next(-1);break;case'checkout':this.finishCheckout();break;}}
 toast(message){const t=this.shadowRoot.querySelector('.toast');if(!t)return;t.textContent=message;t.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('visible'),4200);}
 modal(body){this.previousFocus=this.shadowRoot.activeElement;this.shadowRoot.getElementById('modal-root').innerHTML=`<dialog><button class="modal-close" data-action="close" aria-label="Cerrar">${icon('close')}</button>${body}</dialog>`;const d=this.shadowRoot.querySelector('dialog');d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.closeModal();}});d.addEventListener('cancel',e=>{e.preventDefault();this.closeModal();});d.showModal();}
 closeModal(){this.stopTool?.();this.shadowRoot.querySelector('dialog')?.close();this.shadowRoot.getElementById('modal-root').innerHTML='';this.previousFocus?.focus();}
 checkout(id){this.checkoutBeat=this._beats.find(b=>b.id===id);if(!this.checkoutBeat)return;this.selectedLicense='basic';const b=this.checkoutBeat;this.modal(`<div class="eyebrow">DA EL SIGUIENTE PASO</div><h2>Hazlo tuyo.</h2><div class="checkout-beat">${this.art(b)}<div><h3>${esc(b.title)}</h3><p>${esc(this.producer(b).name)} · ${b.bpm} BPM</p></div></div><fieldset><legend>Elige tu licencia</legend><label class="license"><input type="radio" name="license" value="basic" checked><span><strong>Basic</strong><small>MP3 · Uso no exclusivo</small></span><b>${money(b.price)}</b></label><label class="license"><input type="radio" name="license" value="premium"><span><strong>Premium</strong><small>WAV + stems · Uso no exclusivo</small></span><b>${money(b.premiumPrice??b.price*2)}</b></label></fieldset><p class="license-note">${this.hasAttribute('demo')?'Licencias de ejemplo. Los límites de uso se acuerdan con cada productor.':'Consulta los términos del productor antes de comprar.'}</p><div id="checkout-summary"></div><p class="checkout-error" role="alert"></p><button class="primary wide" data-action="checkout">${this.hasAttribute('demo')?'Simular compra':'Continuar al pago'} ${icon('arrow')}</button><small class="modal-note">${this.hasAttribute('demo')?'Modo demostración · No se realizará ningún cobro.':'El pago y la entrega se gestionan en la aplicación principal.'}</small>`);this.updateCheckout();}
 updateCheckout(){const b=this.checkoutBeat;const s=splitPayment(this.selectedLicense==='premium'?(b.premiumPrice??b.price*2):b.price);this.shadowRoot.getElementById('checkout-summary').innerHTML=`<div class="summary-line"><span>Para el productor (90%)</span><span>${money(s.producer)}</span></div><div class="summary-line"><span>Comisión Beatplace (10%)</span><span>${money(s.platform)}</span></div><div class="summary-total"><strong>Total <small>USD</small></strong><strong>${money(s.total)}</strong></div>`;}
 async finishCheckout(){const b=this.checkoutBeat;const request={beatId:b.id,license:this.selectedLicense,currency:'USD'};const btn=this.shadowRoot.querySelector('[data-action="checkout"]');btn.disabled=true;try{if(this.hasAttribute('demo')){this.state.purchased=[...new Set([...this.state.purchased,b.id])];this.save();this.emit('demo-purchase',request);this.closeModal();this.toast('Compra de demostración guardada en Mis compras.');this.updateContent();}else if(typeof this.onCheckout==='function'){await this.onCheckout(request);this.closeModal();}else{this.emit('checkout-request',request);throw new Error('La aplicación debe conectar el servicio de pago para continuar.');}}catch(error){const el=this.shadowRoot.querySelector('.checkout-error');if(el)el.textContent=error.message||'No se pudo iniciar el pago.';}finally{if(btn.isConnected)btn.disabled=false;}}
 showLicense(id){const b=this._beats.find(x=>x.id===id);this.modal(`<div class="eyebrow">TU BIBLIOTECA</div><h2>${esc(b.title)}</h2><p>${this.hasAttribute('demo')?'Esta compra es de demostración y no concede derechos de uso ni archivos comerciales.':'Consulta y descarga tu licencia desde la aplicación principal.'}</p><button class="primary wide" id="request-license">${this.hasAttribute('demo')?'Entendido':'Abrir licencia'}</button>`);this.shadowRoot.getElementById('request-license').onclick=()=>{if(!this.hasAttribute('demo'))this.emit('license-request',{beatId:id});this.closeModal();};}
 upload(){this.modal(`<div class="eyebrow">CREA. COMPARTE. CONECTA.</div><h2>Tu sonido, al mundo.</h2><p class="subtext">Publica un beat y recibe el 90% de cada venta.</p><form id="publish-form"><label>Título del beat<input name="title" required maxlength="70" placeholder="Dale un nombre a tu sonido"></label><label>Nombre del productor<input name="producerName" required maxlength="50" placeholder="Tu nombre artístico"></label><div class="form-grid"><label>Género<select name="genre">${genres.slice(1).map(g=>`<option>${g}</option>`).join('')}</select></label><label>BPM<input name="bpm" type="number" min="40" max="240" value="120" required></label><label>Tonalidad<select name="key">${['Do','Re','Mi','Fa','Sol','La','Si'].flatMap(n=>['menor','mayor'].map(k=>`<option>${n} ${k}</option>`)).join('')}</select></label><label>Precio Basic (USD)<input name="price" type="number" min="1" max="10000" step=".01" value="29" required></label></div><label class="file-label">${icon('upload')} Vista previa de audio<input name="audio" type="file" accept="audio/*,.wav,.mp3,.ogg,.m4a" required><small>MP3, WAV u OGG · Hasta 20 MB</small></label><label class="consent"><input type="checkbox" name="rights" required><span>Confirmo que tengo los derechos para publicar este beat.</span></label><p class="publish-error" role="alert"></p><button class="primary wide" type="submit">${this.hasAttribute('demo')?'Publicar en la demo':'Publicar beat'} ${icon('arrow')}</button><small class="modal-note">${this.hasAttribute('demo')?'El audio permanece en este navegador durante esta sesión.':'La app principal guardará el audio y los datos del beat.'}</small></form>`);}
 async onSubmit(e){if(await this.socialSubmit?.(e))return;if(e.target.id!=='publish-form')return;e.preventDefault();const f=new FormData(e.target);const file=f.get('audio');const error=this.shadowRoot.querySelector('.publish-error');if(!file?.size||file.size>20*1024*1024){error.textContent='Selecciona un audio de hasta 20 MB.';return;}if(!file.type.startsWith('audio/')&&!/\.(wav|mp3|ogg|m4a)$/i.test(file.name)){error.textContent='El archivo debe ser un audio compatible.';return;}const title=f.get('title').trim(),producerName=f.get('producerName').trim();if(!title||!producerName){error.textContent='Completa el título y el nombre del productor.';return;}const btn=e.target.querySelector('[type="submit"]');btn.disabled=true;const data={title,producerName,genre:f.get('genre'),bpm:Number(f.get('bpm')),key:f.get('key'),price:Number(f.get('price')),audio:file};try{let beat;if(this.hasAttribute('demo')){const url=URL.createObjectURL(file);this.urls.push(url);beat={...data,audio:undefined,id:crypto.randomUUID(),producerId:crypto.randomUUID(),art:'fuego',plays:0,previewUrl:url};}else if(typeof this.onPublish==='function'){beat=await this.onPublish(data);if(!beat?.id)throw Error('El servicio debe devolver el beat publicado con su id.');}else{this.emit('publish-request',data);throw Error('La aplicación debe conectar el servicio de publicación.');}this.beats=[beat,...this._beats];this.state.view='catalog';this.state.genre='Todos';this.state.query='';this.state.sort='new';this.render();this.emit('published',{beat});this.toast('Tu beat ya está en el catálogo.');}catch(err){error.textContent=err.message||'No se pudo publicar el beat.';}finally{btn.disabled=false;}}
 destroy(){this.audio.pause();this.audio.src='';this.urls.forEach(url=>URL.revokeObjectURL(url));this.urls=[];this.remove();}
}
installAppearance(BeatPlace);
installSocial(BeatPlace);
if(!customElements.get('beat-place'))customElements.define('beat-place',BeatPlace);
export {BeatPlace};







